services:
  proxy: 
    image: traefik:v3.1.2
    command: 
      - --providers.docker
      - --api.insecure=true 
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:5174
    ports:
      - "80:80"
      - "5174:5174"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
        
  server:
    image: server-sample
    build: 
      context : ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    labels:
      - traefik.http.routers.server.rule=(Host(`${HOST}`) && PathPrefix(`/api`))
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.services.server.loadbalancer.server.port=5174
    restart: always
    networks:
      - app-network
    environment:
      - TZ=Europe/Paris # Définir la zone horaire
    volumes:
      - /etc/localtime:/etc/localtime:ro # Synchroniser l'heure avec l'hôte 

  client:
    image: client-sample
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    networks:
      - app-network
    labels:
      - "traefik.http.routers.client.rule=Host(`${HOST}`)"
      - "traefik.http.routers.client.entrypoints=web"
      - "traefik.http.services.client.loadbalancer.server.port=80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro # Synchroniser l'heure avec l'hôte 



networks:
  app-network: